### ISSUE TITLE
Prompt input?

### ISSUE THREAD

**Issue by radames** [tairov/llama2.mojo#11]
Hi @tairov great work here!
I notice you're not using the prompt, it would be fun to be able to input it, I could add it to the #10

**Comment by tairov** [comment]
Hi @radames , thanks for sending PR, I'll take a look tomorrow. 
Yeah, I didn't have a chance to implement one more fn for prompt support. 
Would you mind to create another PR for prompt input? thanks!

**Comment by radames** [comment]
If you implement the step on Mojo, I can also add the Gradio UI part of it!
one thing I could find on Mojo Docs was how to use `argv` 🤦🏼
but this worked on my tests
```
    let os = Python.import_module("os")
    let prompt = os.environ.get('PROMPT', "")
```

**Comment by tairov** [comment]
Probably that's why I haven't ported prompt part right away from llama2.py , because it was not clear how to read args
I would implement it like in llama2.c with arg names .

**Comment by trevorhobenshield** [comment]
You can read in args like this:

```mojo
from sys import argv

fn main() raises:
    let args = argv()
    print(args[1])
```

```bash
mojo main.mojo foo
```

**Comment by tairov** [comment]
prompt support added 
@radames could you add changes to gradio app as well? 
Is it possible to execute it cli in this way via gradio app?  
```
mojo llama2.mojo stories15M.bin -s 100 -n 256 -t 0.5 -i "Llama is an animal"
```

**Comment by radames** [comment]
awesome @tairov I'll do it as soon as I can!
