### ISSUE TITLE
Can a RestAPI be built

### ISSUE THREAD

**Issue by StudyingLover** [tairov/llama2.mojo#17]
The fast llama2 reasoning is really helpful to us, but how to add a RestAPI to mojo, preferably one that is compatible with the openai interface? I don't know much about mojo. I know how to use python flask. Can you help me?

**Comment by hungtooc** [comment]
same here

**Comment by tairov** [comment]
I haven't researched this topic. I can suggest to look for something similar but for `llama2.c`
