### ISSUE TITLE
Mojo: error: execution exited with a non-zere result:1

### ISSUE THREAD

**Issue by Cyria7** [tairov/llama2.mojo#18]
The error occurs when running llama.mojo
My environment: Python  3.10(ubuntu22.04)

console imformation bellow:
>  mojo llama2.mojo stories15M.bin -s 100 -n 256 -t 0.5 -i "Llama is an animal"
num hardware threads:  192  SIMD vector width:  16
Unhandled exception caught during execution: An error occurred in Python.
mojo: error: execution exited with a non-zero result: 1

**Comment by tairov** [comment]
Hi @Cyria7 , probably you haven't downloaded model file `stories15M.bin`
See how it works on HF https://huggingface.co/spaces/radames/Gradio-llama2.mojo
