### ISSUE TITLE
Error executing mojo llama2.mojo

### ISSUE THREAD

**Issue by mpage38** [tairov/llama2.mojo#2]
After having installed mojo (working), and llama2 as described, running `mojo llama2.mojo` on ubuntu 22.04 with 16 cores, I get:

llama2.mojo $ mojo llama2.mojo 
num hardware threads:  16  SIMD vector width:  16
checkpoint size:  60816028
Unhandled exception caught during execution: An error occurred in Python.
mojo: error: execution exited with a non-zero result: 1

**Comment by tairov** [comment]
Hi @mpage38 , thanks for opening this issue. 
Yeah, I got ton of messages like this during my implementation. Did you have a stack dumped? Could you please make sure you have `llvm-symbolizer` installed on your system. And then share the stack trace.

Also did you tried any examples from Mojo to execute on you environment?

As a workaround I can suggest to upload `llama2.mojo` & `read` module directory to modular playground (just copy `llaam2.mojo` content to the notebook), there you need to upload `stories15M.bin` to playground as well. It was working fine in playground.

**Comment by raxbits** [comment]
> Hi @mpage38 , thanks for opening this issue. Yeah, I got ton of messages like this during my implementation. Did you have a stack dumped? Could you please make sure you have `llvm-symbolizer` installed on your system. And then share the stack trace.
> 
> Also did you tried any examples from Mojo to execute on you environment?
> 
> As a workaround I can suggest to upload `llama2.mojo` & `read` module directory to modular playground (just copy `llaam2.mojo` content to the notebook), there you need to upload `stories15M.bin` to playground as well. It was working fine in playground.

i have llvm 14 (and symbolizer) installed , still getting same. mojo 0.2.1 (64d14e85) is version.

**Comment by tairov** [comment]
@raxbits could you share stack trace?

**Comment by raxbits** [comment]
> @raxbits could you share stack trace?

sure. 1 sec.
[strace_output.txt](https://github.com/tairov/llama2.mojo/files/12580670/strace_output.txt)

**Comment by tairov** [comment]
@raxbits `Linux Mint 21.2` ? 
I think mojo currently supports only Ubuntu OS
please see this : https://docs.modular.com/mojo/manual/get-started/#system-requirements

**Comment by ZeroHackz** [comment]
Ngl I have the same issue on Ubuntu 22.04. 
![tempsnip](https://github.com/tairov/llama2.mojo/assets/15
These are the commands I used.
![tempsnip2](https://github.com/tairov/llama2.mojo/assets/15729496/a5bc15fc-a84c-462a-9c59-7512ec504939)
729496/de4b8d17-3e29-4a88-afaa-450ade534db1)
 Everything installed succesfully also on version 14 LLVM.
Mind sharing a bit more about your setup?

**Comment by tairov** [comment]
@ZeroHackz I think I just used standard instructions from this page https://docs.modular.com/mojo/manual/get-started/index.html
And then just separately I installed `llvm-symbolizer`


The error message you shared says `An error occured in Python`, probably this could be related to `MOJO_PYTHON_LIBRARY` env variable. 

Which version of Python do you have ?
Can you execute successfully [mojo/examples](https://github.com/modularml/mojo/tree/main/examples)? 

Try to follow instructions from this repo https://github.com/trevorhobenshield/mojodojo

If it won't help, I think the only way is to debug the code by switching off python related lines

**Comment by raxbits** [comment]
> @raxbits `Linux Mint 21.2` ? I think mojo currently supports only Ubuntu OS please see this : https://docs.modular.com/mojo/manual/get-started/#system-requirements

fair. r u able to dockerize ur app? can help a ton. thanks!

**Comment by g1y5x3** [comment]
> Try to follow instructions from this repo https://github.com/trevorhobenshield/mojodojo

I followed the instructions but unfortunately it didn't help. Also running on `Ubuntu 22.04`

**Comment by tairov** [comment]
@mpage38 @raxbits @ZeroHackz could you guys confirm , is the issue disappear after pulling latest changes? Essentially this repo didn't contain `tokenizer.bin`

And yes, Mojo is still in early stages.. I think I need to add some pre-checks and print nice messages if some files couldn't be found or broken.

**Comment by raxbits** [comment]
> @mpage38 @raxbits @ZeroHackz could you guys confirm , is the issue disappear after pulling latest changes? Essentially this repo didn't contain `tokenizer.bin`
> 
> And yes, Mojo is still in early stages.. I think I need to add some pre-checks and print nice messages if some files couldn't be found or broken.

just pulled and seems fixed :+1:
