### ISSUE TITLE
Is llama2 a group query attention or multi head attention?

### ISSUE THREAD

**Issue by magician-blue** [tairov/llama2.mojo#23]
I remember llama2 uses group query attention. In the llama.c, I found there are kv_heads, kv_dim.

**Comment by tic-top** [comment]
In [run.c](https://github.com/karpathy/llama2.c/blob/master/run.c), I find something like this.
`
 // qkv matmuls for this position
        matmul(s->q, s->xb, w->wq + l*dim*dim, dim, dim);
        matmul(s->k, s->xb, w->wk + l*dim*kv_dim, dim, kv_dim);
        matmul(s->v, s->xb, w->wv + l*dim*kv_dim, dim, kv_dim);
`

**Comment by tairov** [comment]
Thanks for you question. I found this issue in the original [llama repo](https://github.com/facebookresearch/llama/issues/384) quite interesting  . Probably need to revise & adapt our implementation. 
@magician-blue did you implement similar approach in you recent PR?

**Comment by magician-blue** [comment]
#24
