### ISSUE TITLE
it is taking python 3.6 insted of 3.9.18

### ISSUE THREAD

**Issue by ysh-rawat-11** [tairov/llama2.mojo#33]
/home/y3rawat/.modular/pkg/packages.modular.com_mojo/bin/mojo /home/y3rawat/mojo/llama2.mojo
/home/y3rawat/mojo/llama2.mojo:10:6: error: unable to locate module 'read'
from read import BufReader, File
     ^
/home/y3rawat/.modular/pkg/packages.modular.com_mojo/bin/mojo: error: failed to parse the provided Mojo
(python38) y3rawat@y3rawat-ASUS-TUF-Gaming-F15-FX507ZC4-FX507ZC4:~/mojo$

**Comment by tairov** [comment]
hi @ysh-rawat-11  are you sure you have pulled all files from this repo?

**Comment by ysh-rawat-11** [comment]
(python38) y3rawat@y3rawat-ASUS-TUF-Gaming-F15-FX507ZC4-FX507ZC4:~/Documents/llama2.mojo-master$ /home/y3rawat/.modular/pkg/packages.modular.com_mojo/bin/mojo /home/y3rawat/Documents/llama2.mojo-master/llama2.mojo
num hardware threads:  12
SIMD vector width:  16
Usage: mojo llama2.mojo <checkpoint> [options]
Example: mojo llama2.mojo stories15M.bin -s 99 -n 256 -t 0.5 -i "Llama is an animal"
Options:
  -s <int>    random seed, default time.now()
  -t <float>  temperature in [0,1.0], default 1.0
  -n <int>    number of steps to run for, default 256. 0 = max_seq_len
  -i <string> input prompt
  -z          tokenizer path
  -r <string> rope architecture, default 'llama' for llama rope, 'falcon' for falcon rope
(python38) y3rawat@y3rawat-ASUS-TUF-Gaming-F15-FX507ZC4-FX507ZC4:~/Documents/llama2.mojo-master$ mojo llama2.mojo stories15M.bin -s 100 -n 256 -t 0.5 -i "Llama is an animal"
Invalid command "llama2.mojo".
(python38) y3rawat@y3rawat-ASUS-TUF-Gaming-F15-FX507ZC4-FX507ZC4:~/Documents/llama2.mojo-master$

**Comment by tairov** [comment]
I guess you have installed some wrong binary instead of mojo sdk..
