### ISSUE TITLE
Do you have a plan to port Stable Diffusion models to mojo?

### ISSUE THREAD

**Issue by linhduongtuan** [tairov/llama2.mojo#55]
Hi @tairov,

I love your work so much and thank you for your contribution. 

I think mojo is very promising in the near future. And I am wondering that do you have any plan to port Stable Diffusion models to mojo? Or do you know someone is currently do this?

Best, 
Linh

**Comment by tairov** [comment]
Hi @linhduongtuan , thanks for you question
I don't have any plans to port Stable Diffusion. If you feel that's a project you could take on, go ahead and initiate it. I think the Mojo community would be happy to provide support ;)
