### ISSUE TITLE
Unroll vectorisation

### ISSUE THREAD

**Issue by miili** [tairov/llama2.mojo#56]
Hi there,

awesome port and demonstrator. Have you compared the performance of `vectorize` and `vectorize_unroll`?

While tinkering around with demanding algos I saw that unrolling the partial loop 12x I got a 10% performance increase. Maybe enough to beat cpp? 😁

**Comment by tairov** [comment]
Hi @miili ! Sound amazing :)

I was keeping my eye on `vectorize_unroll` as well as to some other incredible features of Mojo , like autotune, tiles and alignment. But I didn't have bandwidth to try out all cases . I would be really cool if you can share a PR, I'd love to merge
