### ISSUE TITLE
HuggingFace demo not working

### ISSUE THREAD

**Issue by avi-cenna** [tairov/llama2.mojo#58]
Hi,

The [HuggingFace](https://huggingface.co/spaces/radames/Gradio-llama2.mojo) demo of this project is not working. It says:

```bash
Build failed with exit code: 1
...
--> ERROR: process "/bin/sh -c curl https://get.modular.com | MODULAR_AUTH=$AUTH_KEY sh -     && modular install mojo" did not complete successfully: exit code: 1
```

**Comment by radames** [comment]
thanks for the ping @tairov, I fixed the Space, now modular needs to run `modular auth `

**Comment by tairov** [comment]
Thanks!
