### ISSUE TITLE
How to use mojo playground to run this model?

### ISSUE THREAD

**Issue by yhyu13** [tairov/llama2.mojo#6]
Hi,

Maybe a stupid question, I couldn't find a way to execute shelll cmd in mojo player ground's console or notebook. How did you manage to run this project in the mojo playground?

Thanks!

**Comment by tairov** [comment]
1. Upload stories15M.bin to playground
2. Upload tokenizer.bin
3. Upload `read` directory
4. Create a notebook
5. Copy paste `llama2.mojo` content to code section 1 for example
6. Add code section 2 and put this call to it `main()`
7. Execute both code sections one by one
