### ISSUE TITLE
How to create my own tokenizer.bin?

### ISSUE THREAD

**Issue by hungtooc** [tairov/llama2.mojo#7]
as title

**Comment by tairov** [comment]
check this out : https://github.com/karpathy/llama2.c/blob/master/tokenizer.py

**Comment by hungtooc** [comment]
> check this out : https://github.com/karpathy/llama2.c/blob/master/tokenizer.py
Thank you, I still don't understand how to use my prompt, which is no longer "once upon a time, there was a little girl named Lily."

**Comment by tairov** [comment]
@hungtooc I haven't implemented prompt method yet. Will do it soon this week.
