### ISSUE TITLE
question:Are these speed comparisons all in CPU mode? Can we add a comparison with GPU?

### ISSUE THREAD

**Issue by xiezhipeng-git** [tairov/llama2.mojo#8]
Are these speed comparisons all in CPU mode? Can we add a comparison with GPU?
Also, if you want to train, you want to use Mojo training. Is it necessary to add training related code in this way? Will rewriting be time-consuming?

**Comment by tairov** [comment]
Yes, all in CPU mode only.
I would love to make it working on GPU.. But unfortunately Mojo doesn't support GPU execution yet.
