### ISSUE TITLE
Add support for mojo 0.6

### ISSUE THREAD

**Issue by clarkezone** [tairov/llama2.mojo#80]
I know it only came out yesterday but ;-)

**Comment by tairov** [comment]
Hi @clarkezone !
Do you see any issues with running it on Mojo 0.6.0?
It looks working fine on my side .

Also do you have any suggestions which new Mojo features you'd like to see implemented in llama2.🔥?

**Comment by clarkezone** [comment]
> Hi @clarkezone !
> Do you see any issues with running it on Mojo 0.6.0?
> It looks working fine on my side .
> 
> Also do you have any suggestions which new Mojo features you'd like to see implemented in llama2.🔥?

Just tested if with 0.6 on AMD64 linux and it appears to work fine.  So probably safe to bump the readme.

I haven't looked at the llama2.🔥 code yet and still working my way through the 🔥 0.6 readme.  So not yet but will do for sure ;-). Nice job with this and getting into the keynote.  Now we just need a port of whisper-cpp ;-)
